# File my_app/docker-compose.yml
version: '3'

networks:
  internal:
    external: false

services:
  app:
    image: hello_docker_heroku:0.1.0
    build:
      context: .
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE} # export SECRET_KEY_BASE=$(mix phx.gen.secret)
      - DATABASE_DB=${DATABASE_DB} # same as release.exs export DATABASE_DB=hello_docker_heroku_dev
      - DATABASE_HOST=db
    ports:
      - 4000:4000
    networks:
      - internal
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=${DATABASE_DB}
    networks:
      - internal
